### ISSUE TITLE
QUESTION - should "using_X" configuration be overridden by models: enabled: configuration in dbt_project.yml?

### ISSUE THREAD

**Issue by raubrey2014** [fivetran/dbt_quickbooks_source#20]
**Are you a Fivetran customer?** 
Yes! - Ryan Aubrey, software engineer, Outlast

**Your Question**
Hi there! My company is using this package to manage our Quickbooks transformations in our data warehouse.

In Quickbooks, we do not use the Refund Receipt functionality - setting the environment variable `using_receipt_refund` works great to pass over the models dependent on refund receipts! Until we need to enable/disable the quickbooks models overall per dev/prod environment that is...

TLDR: `using_X` var is being overridden. Do you have any suggestions on how we can get the intended functionality?

- Quickbooks disabled overall in all environments except for "prod"
- Refund Receipts models always disabled

### Context

```
vars:
  using_refund_receipt: false

models:
  quickbooks:
    enabled: "{{ (target.name == 'prod') | as_bool }}"

  quickbooks_source:
    enabled: "{{ (target.name == 'prod') | as_bool }}"
```

As you can see, we want to _disable_ the refund receipt module **always**, as well as only ever enable quickbooks models in our "prod" environment. The above configuration gives precedence to the models>quickbooks>enabled: true when in our production environment.

This means that with the above configuration, when deploying our models to our production environment dbt _still tries to deploy the models related to refund receipts_.

Do you have any suggestions on how we can get the intended functionality?
- Quickbooks disabled overall in all environments except for "prod"
- Refund Receipts models always disabled

<hr />

### Solutions I tried

I tried disabling individual models, but the list is.. long :) 
```
models:
  quickbooks:
    enabled: "{{ (target.name == 'prod') | as_bool }}"

  quickbooks_source:
    enabled: "{{ (target.name == 'prod') | as_bool }}"
     stg_quickbooks__refund_receipt_tmp:
       enabled: false
     stg_quickbooks__refund_receipt:
       enabled: false
    ...
```

Any help here is very much appreciated!
